/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_miguelblanco;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author migue
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genero = new javax.swing.ButtonGroup();
        popup_agregararbol = new javax.swing.JPopupMenu();
        agregaralarbol = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tf_nombre = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        ftf_numcuenta = new javax.swing.JFormattedTextField();
        sp_edad = new javax.swing.JSpinner();
        rb_masculino = new javax.swing.JRadioButton();
        rb_femenino = new javax.swing.JRadioButton();
        cb_carrera = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_jefe = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_personas = new javax.swing.JList<>();
        ftf_precio = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_personas = new javax.swing.JTree();

        agregaralarbol.setText("Agregar al Arbol");
        agregaralarbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregaralarbolMouseClicked(evt);
            }
        });
        agregaralarbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregaralarbolActionPerformed(evt);
            }
        });
        popup_agregararbol.add(agregaralarbol);

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        try {
            ftf_numcuenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        Genero.add(rb_masculino);
        rb_masculino.setSelected(true);
        rb_masculino.setText("M");

        Genero.add(rb_femenino);
        rb_femenino.setText("F");

        cb_carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Finanzas ", "Derecho", "Administracion de Empresas", "Diseño Grafico", "Mercadotecnia", "Sistemas Computacionales", "Industrial y de Sistemas", "Mecatronica", "Biomedica", "Energia", "Medicina y Cirugia", "Odontologia", "Nutricion", "Terapia Fisica y Ocupacional" }));

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Numero Cuenta");

        jLabel4.setText("Edad");

        jLabel5.setText("Genero");

        jLabel6.setText("Carrera");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Precio");

        jLabel8.setText("Jefe de Carrera");

        jl_personas.setModel(new DefaultListModel());
        jl_personas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_personasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_personas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 554, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftf_numcuenta)
                            .addComponent(tf_nombre)
                            .addComponent(tf_apellido)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rb_masculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_femenino))
                            .addComponent(tf_jefe)
                            .addComponent(ftf_precio))))
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftf_numcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_masculino)
                    .addComponent(rb_femenino)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ftf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Estudiantes", jPanel1);

        jScrollPane3.setViewportView(jList1);

        jLabel9.setText("Nombre");

        jLabel10.setText("Apellido");

        jLabel11.setText("Salario");

        jLabel12.setText("Edad");

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Maestros ", jPanel2);

        jScrollPane4.setViewportView(jList2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 293, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clases", jPanel4);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Carreras");
        jt_personas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_personas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Arbol", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String anombre = tf_nombre.getText();
            String aapellido = tf_apellido.getText();
            int anumcuenta = Integer.parseInt(ftf_numcuenta.getText());
            int aedad = (Integer) sp_edad.getValue();
            String agenero;
            if (rb_masculino.isSelected()) {
                agenero = "Masculino";
            } else {
                agenero = "Femenino";
            }
            double aprecio = Double.parseDouble(ftf_precio.getText());
            String ajefe = tf_jefe.getText();
            Carrera acarrera = new Carrera();
            if (cb_carrera.getSelectedIndex() <= 4) {
                switch (cb_carrera.getSelectedIndex()) {

                    case 0:
                        acarrera = new Licenciatura("Finanzas", "Licenciatura", aprecio, ajefe);
                        break;
                    case 1:
                        acarrera = new Licenciatura("Derecho", "Licenciatura", aprecio, ajefe);
                        break;
                    case 2:
                        acarrera = new Licenciatura("Administracion de Empresas", "Licenciatura", aprecio, ajefe);
                        break;
                    case 3:
                        acarrera = new Licenciatura("Diseño Grafico", "Licenciatura", aprecio, ajefe);
                        break;
                    case 4:
                        acarrera = new Licenciatura("Mercadotecnia", "Licenciatura", aprecio, ajefe);
                        break;
                    default:
                        break;
                }
            } else if (cb_carrera.getSelectedIndex() <= 9) {
                switch (cb_carrera.getSelectedIndex()) {
                    case 5:
                        acarrera = new Ingenieria("Sistemas Computacionales", "Ingenieria", aprecio, ajefe);
                        break;
                    case 6:
                        acarrera = new Ingenieria("Industrial y de Sistemas", "Ingenieria", aprecio, ajefe);
                        break;
                    case 7:
                        acarrera = new Ingenieria("Mecatronica", "Ingenieria", aprecio, ajefe);
                        break;
                    case 8:
                        acarrera = new Ingenieria("Biomedica", "Ingenieria", aprecio, ajefe);
                        break;
                    case 9:
                        acarrera = new Ingenieria("Energia", "Ingenieria", aprecio, ajefe);
                        break;
                    default:
                        break;
                }
            } else if (cb_carrera.getSelectedIndex() <= 13) {
                switch (cb_carrera.getSelectedIndex()) {
                    case 10:
                        acarrera = new CienciasdelaSalud("Medicina y Cirugia", "Ciencias de la Salud", aprecio, ajefe);
                        break;
                    case 11:
                        acarrera = new CienciasdelaSalud("Odontologia", "Ciencias de la Salud", aprecio, ajefe);
                        break;
                    case 12:
                        acarrera = new CienciasdelaSalud("Nutricion", "Ciencias de la Salud", aprecio, ajefe);
                        break;
                    case 13:
                        acarrera = new CienciasdelaSalud("Terapia Fisica y Ocupacional", "Ciencias de la Salud", aprecio, ajefe);
                        break;
                    default:
                        break;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ninguna carrera fue seleccionada!");
            }
            // TODO add your handling code here:
            Estudiantes temp = new Estudiantes(anombre, aapellido, anumcuenta, aedad, agenero, acarrera);
            estuadiantes.add(temp);

            DefaultListModel modelo = (DefaultListModel) jl_personas.getModel();
            modelo.addElement(temp);
            jl_personas.setModel(modelo);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jl_personasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_personasMouseClicked
        if (jl_personas.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                popup_agregararbol.show(evt.getComponent(), evt.getX(), evt.getY());

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_personasMouseClicked

    private void agregaralarbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregaralarbolMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_agregaralarbolMouseClicked

    private void agregaralarbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregaralarbolActionPerformed
        try {
            if (jl_personas.getSelectedIndex() >= 0) {
                DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_personas.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
                //obtener la persona a guardar
                DefaultListModel modeloLISTA = (DefaultListModel) jl_personas.getModel();
                String estudiante, carrera, facultad;
                estudiante = ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).getNombre() + " " + ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).getApellido();
                carrera = ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).getCarrera().getNombre();
                facultad = ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).getCarrera().getFacultad();
                int centinela = -1, centinela2 = -1, centinela3 = -1;

                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (raiz.getChildAt(i).toString().equals(facultad)) {
                        for (int j = 0; j < raiz.getChildAt(i).getChildCount(); j++) {

                            if (raiz.getChildAt(i).getChildAt(j).toString().equals(carrera)) {
                                for (int k = 0; k < 2; k++) {
                                    if (raiz.getChildAt(i).getChildAt(j).getChildAt(k).toString().equals("Estudiante")) {
                                        DefaultMutableTreeNode l = new DefaultMutableTreeNode(estudiante);
                                        ((DefaultMutableTreeNode) raiz.getChildAt(i).getChildAt(j).getChildAt(k)).add(l);
                                        centinela2 = 1;
                                        j = raiz.getChildAt(i).getChildCount();
                                        centinela3 = 1;
                                    }
                                }
                                if (centinela3 == -1) {
                                    DefaultMutableTreeNode p = new DefaultMutableTreeNode("Estudiante");
                                    DefaultMutableTreeNode k = new DefaultMutableTreeNode(estudiante);
                                    p.add(k);
                                    ((DefaultMutableTreeNode) raiz.getChildAt(i).getChildAt(j)).add(p);
                                    centinela2 = 1;
                                    j = raiz.getChildAt(i).getChildCount();
                                }
                            }

                        }

                        if (centinela2 == -1) {
                            DefaultMutableTreeNode p = new DefaultMutableTreeNode(carrera);
                            DefaultMutableTreeNode w = new DefaultMutableTreeNode("Estudiante");
                            DefaultMutableTreeNode x = new DefaultMutableTreeNode(estudiante);
                            w.add(x);
                            p.add(w);
                            ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                        }

                        i = raiz.getChildCount();
                        centinela = 1;
                    }

                }

                if (centinela == -1) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(facultad);
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(carrera);
                    DefaultMutableTreeNode m = new DefaultMutableTreeNode("Estudiante");
                    DefaultMutableTreeNode j = new DefaultMutableTreeNode(estudiante);
                    m.add(j);
                    p.add(m);
                    n.add(p);
                    raiz.add(n);
                }  // fin if      

                modeloARBOL.reload();

            } else {
                JOptionPane.showMessageDialog(this,
                        "No hay persona seleccionada");
            }

        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_agregaralarbolActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_personas.getModel();

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String mnombre = jTextField1.getText();
        String mapellido = jTextField2.getText();
        double msalario = Double.parseDouble(jTextField3.getText());
        int medad = (Integer) jSpinner1.getValue();
        Maestros temp = new Maestros(mnombre, mapellido, msalario, medad);
        maestros.add(temp);

        DefaultListModel modelo = (DefaultListModel) jList1.getModel();
        modelo.addElement(temp);
        jList1.setModel(modelo);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Genero;
    private javax.swing.JMenuItem agregaralarbol;
    private javax.swing.JComboBox<String> cb_carrera;
    private javax.swing.JFormattedTextField ftf_numcuenta;
    private javax.swing.JTextField ftf_precio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JList<String> jl_personas;
    private javax.swing.JTree jt_personas;
    private javax.swing.JPopupMenu popup_agregararbol;
    private javax.swing.JRadioButton rb_femenino;
    private javax.swing.JRadioButton rb_masculino;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_jefe;
    private javax.swing.JTextField tf_nombre;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Estudiantes> estuadiantes = new ArrayList();
    public ArrayList<Clases> clases = new ArrayList();
    public ArrayList<Maestros> maestros = new ArrayList();
}
